from opentelemetry import metrics
import logging
from opentelemetry import trace
from backend.observability.monitoring.metrics_store import metrics_store

logger = logging.getLogger(__name__)
tracer = trace.get_tracer(__name__)

# Re-use the existing business meter
business_meter = metrics.get_meter("mulenet.business")

security_suspicious_counter = business_meter.create_counter(
    "security.events.suspicious",
    description="Total number of suspicious activities detected"
)

security_high_risk_counter = business_meter.create_counter(
    "security.events.high_risk",
    description="Total number of high risk predictions"
)

security_blocked_counter = business_meter.create_counter(
    "security.events.blocked",
    description="Total number of blocked requests"
)

security_auth_failures = business_meter.create_counter(
    "security.auth.failures",
    description="Total number of failed authentication attempts"
)

class SecurityMonitor:
    @staticmethod
    def log_suspicious_activity(event_type: str, account_id: str):
        with tracer.start_as_current_span("security_event") as span:
            span.set_attribute("security.event_type", event_type)
            span.set_attribute("security.account_id", account_id)
            security_suspicious_counter.add(1, {"type": event_type})
            metrics_store.increment_security_event("suspicious")
            logger.warning(f"Suspicious activity detected: {event_type} for account {account_id}")

    @staticmethod
    def log_high_risk_prediction(model_name: str, score: float):
        security_high_risk_counter.add(1, {"model": model_name})
        metrics_store.increment_security_event("high_risk")
        logger.warning(f"High risk prediction generated by {model_name}: {score}")

    @staticmethod
    def log_blocked_request(reason: str, ip_address: str):
        security_blocked_counter.add(1, {"reason": reason})
        metrics_store.increment_security_event("blocked")
        logger.error(f"Request blocked from {ip_address}: {reason}")

    @staticmethod
    def log_auth_failure(username: str):
        security_auth_failures.add(1)
        logger.warning(f"Failed authentication attempt for user: {username}")
